version: "3.8"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-mobile-device
    ports:
      - "3310:3306" # FOR DEV PURPOSE ONLY
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=mduser
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=MobileDevice
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 20
    networks:
      - mobile-device-net

  open-liberty:
    build: .
    container_name: open-liberty-mobile-device
    ports:
      - "9080:9080" # FOR DEV AND TEST PURPOSE ONLY
    networks:
      - mobile-device-net
      - common-net
    depends_on:
      mysql:
        condition: service_healthy

networks:
  mobile-device-net:
    driver: bridge
  common-net:
    name: common-net