version: "3.8"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-mobile-device
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=MobileDevice
