version: "3.8"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-resources-management
    #    FOR DEV PURPOSE ONLY
    #    ports:
    #      - "3312:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rmuser
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=ResourcesManagement
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 20
    networks:
      - resources-management-net

  open-liberty:
    build: .
    container_name: open-liberty-resources-management
    #    FOR DEV AND TEST PURPOSE ONLY
    #    ports:
    #      - "9082:9082"
    networks:
      - resources-management-net
      - common-net
    depends_on:
      mysql:
        condition: service_healthy

networks:
  resources-management-net:
    driver: bridge
  common-net:
    external: true
    name: common-net