version: "3.8"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-resources-management
    ports:
      - "3312:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rmuser
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=ResourcesManagement
